name: Publish Python 🐍 distributions 📦 to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  extract-tag:  
    runs-on: ubuntu-latest  
    outputs:  
      version: ${{ steps.extract_tag.outputs.tag }}  
    steps:  
      - uses: actions/checkout@v4
      - id: extract_tag  
        name: Extract tag name  
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"  

  build-and-publish-pypi:
    needs: [extract-tag]
    runs-on: ubuntu-latest
    environment: 
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: python3 -m pip install setuptools wheel twine
      - name: Update version in setup.py
        run: sed -i 's/version="[^"]*"/version="${{ needs.extract-tag.outputs.version }}"/' setup.py
      - name: Update version in pyproject.toml
        run: sed -i 's/version = "[^"]*"/version = "${{ needs.extract-tag.outputs.version }}"/' pyproject.toml
      - name: Update package name in setup.py  
        run: sed -i 's/name="[^"]*"/name="browser-service"/' setup.py
      - name: Update package name in pyproject.toml
        run: sed -i 's/name = "[^"]*"/name = "browser-service"/' pyproject.toml
      - name: Build a binary wheel
        run: python3 setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          attestations: false
